services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      # 1. Persistent named volume for DB data
      - postgres-data:/var/lib/postgresql/data

      # 2. File mount: init.sql runs only on first init
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    ports:
      - "3000:3000" # host:container
    environment:
      # note calling @ database service name
      DATABASE_URL: postgres://testuser:testuserpassword@postgres:5432/testdb
    depends_on:
      - postgres
# how set up secrets for this?
volumes:
  postgres-data: